Fixed Issue: RViz panel-Planner Parameters move right without scrollbars
ros-planning/moveit pull request #2126
Opened 2020-06-02 09:48 UTC by alexchua0108

As mentioned in #2062 , RViz panel list will auto-scroll to the right. 

- Disabled the properties of "autoScroll" of planner_param_treeview

2020-06-02 09:55 UTC, v4hn commented
Please provide a screenshot while having an edit active.
Why do you increase the *height*?
Can you end up with part of the edit widget outside the view when simply disabling auto scroll?

2020-06-03 06:49 UTC, alexchua0108 commented
> Please provide a screenshot while having an edit active.
> Why do you increase the _height_?
> Can you end up with part of the edit widget outside the view when simply disabling auto scroll?

Please remove the line of increase the _height_
I was using QT designer to edit the property, this might end up increase the Widget Height accidentally.

RViz panel-Planner Parameters will move right without scrollbars is because of the properties of autoScrolls function.
If this property is set to true (the default), the QAbstractItemView automatically scrolls the contents of the view if the user drags within 16 pixels of the viewport edge. If the current item changes, then the view will scroll automatically to ensure that the current item is fully visible.

2020-06-03 09:00 UTC, felixvd commented
Have you tested this? Can you confirm that it works as you expect it to, and post a screenshot of the GUI?

2020-09-21 18:28 UTC, felixvd requested changes
I tested it and it works, just the line about the height is noise and should be removed as suggested.

I actually have the same issue with the Rviz Displays panel, but I don't see these settings in the repository. @rhaschke Do you know where to look?

2020-09-21 19:48 UTC, rhaschke commented
> I actually have the same issue with the Rviz Displays panel.

@felixvd, I'm not sure which issue you are referring to. The (minimal) widget height is automatically calculated by qtdesigner.

2020-09-22 16:58 UTC, felixvd commented
Sorry for the vagueness. I meant the auto-scrolling described in #2062. The content of the Displays panel can scroll horizontally so a part on the left ends up hidden. Here are some screenshots (in the bottom one I scrolled back to the left with the arrow keys):

![Screenshot 2020-09-23 01:54:40](https://user-images.githubusercontent.com/4535737/93913497-2218b400-fd40-11ea-937b-0431d01ae7f8.png)

![Screenshot 2020-09-23 01:55:02](https://user-images.githubusercontent.com/4535737/93913496-21801d80-fd40-11ea-82f3-4bf918cb58a5.png)

2020-09-22 20:28 UTC, rhaschke commented
Ah. I noticed this issue before as well. Could you please file an issue in the rviz repo? I don't know by heart where to look...

2020-09-23 01:55 UTC, felixvd commented
Certainly.

Also this is fixed via #2310 . Thanks for figuring out the solution @alexchua0108 !

2020-09-23 01:55 UTC, closed without merging