Fix OpenMP compilation on OSX with new version of clang
ros-planning/moveit pull request #2474
Opened 2021-01-06 03:21 UTC by Tobias-Fischer

### Description

This PR fixes compilation on OSX with Clang - see See https://stackoverflow.com/questions/46414660/macos-cmake-and-openmp

### Checklist
- [ ] **Required by CI**: Code is auto formatted using [clang-format](http://moveit.ros.org/documentation/contributing/code)
- [ ] Extend the tutorials / documentation [reference](http://moveit.ros.org/documentation/contributing/)
- [ ] Document API changes relevant to the user in the [MIGRATION.md](https://github.com/ros-planning/moveit/blob/master/MIGRATION.md) notes
- [ ] Create tests, which fail without this PR [reference](https://ros-planning.github.io/moveit_tutorials/doc/tests/tests_tutorial.html)
- [ ] Include a screenshot if changing a GUI
- [ ] While waiting for someone to review your request, please help review [another open pull request](https://github.com/ros-planning/moveit/pulls) to support the maintainers

[//]: # "You can expect a response from a maintainer within 7 days. If you haven't heard anything by then, feel free to ping the thread. Thank you!"

2021-01-12 20:40 UTC, tylerjw approved these changes
Looks good to me but I don't have a Mac.  If someone with one could test this that would be apreciated.

2021-01-13 00:32 UTC, Tobias-Fischer commented
We use this in https://github.com/RoboStack/ros-noetic where compilation without this patch fails on OSX, but with the patch it compiles fine.

2021-01-13 10:40 UTC, rhaschke requested changes
Sorry, but this isn't convincing to me. All these settings should be handled by `find_package(OpenMP)`. If there is a bug in OSX's `FindOpenMP.cmake`, it should be fixed there instead of providing a laborious workaround here.
Also, most of the set variables are not used by MoveIt. So why setting them at all?
Could you please report the actual error message(s) as well as the OpenMP variables set in `CMakeCache.txt`?

2021-01-13 19:48 UTC, Tobias-Fischer commented
Hello, I agree that the proper place would be fixing cmake, but years will pass before that fixed version becomes available so it can be used and set as minimum version here.

The error and fix is described there: https://stackoverflow.com/questions/46414660/macos-cmake-and-openmp

We observed the error in our efforts for bringing ROS in conda: https://github.com/RoboStack/ros-noetic
There we have a CI for Linux, Win and OSX. Patching MoveIt with the contents of this PR builds successfully, while not applying the PR leads to the error above.

2021-01-14 08:35 UTC, rhaschke commented
I looked into the stackoverflow link before and the solution you picked is one possible workaround discussed there. But, as I said, this solution is not very convincing to me and it clutters our codebase. There are also comments on stackoverflow stating: 

> CMake can detect the correct OpenMP options for Apple Clang and standard Clang.

So, please, provide the exact error message, so that we can really help.
In any case, you should (also) file an issue / PR to fix `FindOpenMP.cmake` upstream - even if that's only a solution in the long run.

2021-01-14 10:12 UTC, Tobias-Fischer commented
The exact error message is: 
```
-- Could NOT find OpenMP_C (missing: OpenMP_C_FLAGS OpenMP_C_LIB_NAMES) (found version "1.0")
-- Could NOT find OpenMP_CXX (missing: OpenMP_CXX_FLAGS OpenMP_CXX_LIB_NAMES) (found version "1.0")
```

I can understand that you're worried re code cluttering. Please feel free to either leave a stale PR here or close the PR - I guess people who run into this problem will find the PR and can apply the patch manually. We manually fix it in the Robostack and hopefully this will be the main way of using ROS/MoveIt on OSX soon, there users won't have to worry.

2021-01-14 10:29 UTC, rhaschke commented
The underlying reason of the failure on MacOS seems to be this: http://stechschulte.net/2016/03/20/openmp-osx-cmake.html.
Please, try to use clang-omp as your compiler as suggested there.
In any case, manually setting all the OpenMP variables defeats the purpose of `find_package`! Thus, I'm still not supporting this PR.

2021-01-16 00:13 UTC, mamoll commented
The failure to correctly detect OpenMP appears to be a Home Brew failure, not a macOS failure. The same `find_package(OpenMP)` seems to work just fine with clang installed via MacPorts:
```
env CXX=/opt/local/bin/clang++-mp-11 cmake ...
...
-- Found OpenMP_CXX: -fopenmp=libomp (found version "5.0") 
-- Found OpenMP: TRUE (found version "5.0")  
...
```

2021-01-16 12:47 UTC, rhaschke commented
So, can we close this PR?

2021-03-04 11:23 UTC, v4hn commented
Close due to inactivity.

2021-03-04 11:23 UTC, closed without merging