Warn empty state
ros-planning/moveit pull request #2541
Opened 2021-03-08 14:41 UTC by FabianSchuetze

### Description

I added a warning upon calling [`computeIKService`](https://github.com/FabianSchuetze/moveit/blob/30a170f224c37fc1f28de1640b8da0b3afef6614/moveit_ros/move_group/src/default_capabilities/kinematics_service_capability.cpp#L145) with a [`GetPositionIK::Request` message](http://docs.ros.org/en/hydro/api/moveit_msgs/html/msg/PositionIKRequest.html) without explicitly setting the robot state. The PR warns if the passed `joint state` is empty since this element seems to be the crucial ingredients to me. The error message mentioned in the [ROS-Answers question](https://answers.ros.org/question/371571/found-empty-jointstate-message/) is caused by the following check in [_robotStateMsgToRobotStateHelper](https://github.com/FabianSchuetze/moveit/blob/30a170f224c37fc1f28de1640b8da0b3afef6614/moveit_core/robot_state/src/conversions.cpp#L373):
```c++
  if (!rs.is_diff && rs.joint_state.name.empty() && rs.multi_dof_joint_state.joint_names.empty())
  {
    ROS_ERROR_NAMED(LOGNAME, "Found empty JointState message");
    return false;
  }
```

We could also duplicate this check in the service call, but I am not sure if this duplication is valuable. 

I might have misunderstood the issue and therefore implemented the wrong patch. I am grateful for any hints or suggestions for how to improve the PR! 

### Checklist
- [x] **Required by CI**: Code is auto formatted using [clang-format](http://moveit.ros.org/documentation/contributing/code)
- [ ] Extend the tutorials / documentation [reference](http://moveit.ros.org/documentation/contributing/)
- [ ] Document API changes relevant to the user in the [MIGRATION.md](https://github.com/ros-planning/moveit/blob/master/MIGRATION.md) notes
- [ ] Create tests, which fail without this PR [reference](https://ros-planning.github.io/moveit_tutorials/doc/tests/tests_tutorial.html)
- [ ] Include a screenshot if changing a GUI
- [ ] While waiting for someone to review your request, please help review [another open pull request](https://github.com/ros-planning/moveit/pulls) to support the maintainers

[//]: # "You can expect a response from a maintainer within 7 days. If you haven't heard anything by then, feel free to ping the thread. Thank you!"

2021-03-09 20:47 UTC, simonschmeisser approved these changes

2021-03-09 20:47 UTC, simonschmeisser commented on moveit_ros/move_group/src/default_capabilities/kinematics_service_capability.cpp
> +    ROS_WARN("Empty joint_state position in GetPositionIK::Request msgs. Starting from the current robot state");
```suggestion
    ROS_WARN_NAMED(getName(), "Empty joint_state position in GetPositionIK::Request msgs. Starting from the current robot state");
```
This way messages can be filtered by category and verbosity be selectively reduced.

2021-03-10 11:00 UTC, v4hn requested changes
I strictly prefer #2544 over this approach.

2021-03-10 11:40 UTC, FabianSchuetze commented
I think #2544 is indeed preferable! Thanks for pointing this out!

2021-03-10 11:50 UTC, felixvd commented
Closing because it seems we are in agreement

2021-03-10 11:50 UTC, closed without merging